### ISSUE TITLE
Source code does not compile

### ISSUE THREAD

**Issue by gtezini** [jaymepechan/USDComponentLibrary#1]
Hi,
Please, help me to discover why the source code does not compile. I have notice that some files are missing from project [JABProxy] like [jni.h] and [AccessBridgeDebug.h].

In addition, is it possible to publish some sample codes about how to use the [Microsoft.USD.ComponentLibrary.Hllapi] library?

Thanks in advance.

**Comment by jaymepechan** [comment]
You can ignore these errors if you are not using Java application automation. If you need this component, you need to download and install the Java Access Bridge from Oracle. The installation of this is very detailed and you must follow their instructions exactly and get it working.

The Hllapi library is specific to the Hllapi vendor you are using. Generally the library simply provides actions that match to the functions of Hllapi. If you are unfamiliar with Hllapi, I would look at the vendor documentation. Basically it gives you the ability to read data from specific coordinates of the screen, send keys, read the entire screen contents, etc.

**Comment by gtezini** [comment]
I got it.
Yes, i gonna check the doc from vendor, as you pointed.
Thanks jaymepechan!
